---
- hosts: routeServer1
  gather_facts: no
  become: true

  pre_tasks:
    - name: update apt cache
      raw: apt-get update
      changed_when: false

  tasks:
    - name: Setup FRR
      block:
        - name: Add the key for FRR
          apt_key:
           state: present
           url: https://deb.frrouting.org/frr/keys.asc

        - name: update apt cache
          raw: apt-get update
          changed_when: false

        - name: Install FRR
          apt:
           force: yes
           install_recommends: yes
           name: "{{ item }}"
           state: present
           update_cache: yes
          with_items:
            - frr
            - frr-pythontools